Feature-91 Add linting tests tasks
fundev3/teamup-resumes pull request #7
Opened 2021-07-20 19:54 UTC by rodrigo-baldiviezo-jalafund

2021-07-20 20:09 UTC, almartin1911 requested changes

2021-07-20 20:09 UTC, almartin1911 commented on azure-pipelines.yml
> +- task: DotNetCoreCLI@2
move entire task right before `DotNet Build` tasks please

2021-07-20 20:09 UTC, almartin1911 commented on azure-pipelines.yml
> +  testsProjects: '**/*Tests/*.csproj'
add this variable for me please: `buildConfiguration: $(buildConfiguration)`

we're gonna test using env variables for the pipeline :)

2021-07-20 20:09 UTC, almartin1911 commented on azure-pipelines.yml
> +    projects:  $(testsProjects)
add the `arguments` input right after this line, something like this:
```yml
    arguments: '-c $(buildConfiguration)' 
```

2021-07-20 20:09 UTC, almartin1911 commented on azure-pipelines.yml
>      arguments: '--output $(Build.ArtifactStagingDirectory)'
include the build configuration argument into this call as well, please

2021-07-20 20:09 UTC, almartin1911 commented on azure-pipelines.yml
> +- task: DotNetCoreCLI@2
no, nevermind... left it where it was

2021-07-20 20:37 UTC, martin-callejas-jalafund commented on azure-pipelines.yml
> +  buildConfiguration: $(buildConfiguration)
remove the whole variables sections, but keep the values for the first two, we're gonna add them through Azure interface https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch

2021-07-21 01:43 UTC, martin-callejas-jalafund approved these changes

2021-07-21 01:47 UTC, merged